version: "3.9"

services:
  api:
    image: magnocarlos1988/api-python-uv-project:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minha_api
    ports:
      - "8000:8000"
    networks:
      - project_api_python
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://user:password@db:5432/meubanco

  db:
    image: postgres:18.0-alpine3.22
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: meubanco
    ports:
      - "5432:5432"
    networks:
      - project_api_python
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d meubanco"]
      interval: 5s
      retries: 5
      timeout: 3s

volumes:
  postgres_data:
    name: postgres_data_api_python

networks:
  project_api_python: